#!/usr/bin/env tsx
/**
 * scripts/parse-hooks.ts
 * Reads /home/user/workspace/hooks-library.md, parses each section into
 * category + templates, and outputs supabase/migrations/003_seed_hooks_library.sql
 *
 * Usage: npx tsx scripts/parse-hooks.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Config ──────────────────────────────────────────────
const INPUT_PATH = path.resolve(__dirname, '../../hooks-library.md');
const OUTPUT_PATH = path.resolve(__dirname, '../supabase/migrations/003_seed_hooks_library.sql');

// Map markdown heading → db category slug
const CATEGORY_MAP: Record<string, string> = {
  'EDUCATIONAL': 'educational',
  'COMPARISON': 'comparison',
  'MYTH BUSTING': 'myth_busting',
  'STORYTELLING': 'storytelling',
  'AUTHORITY': 'authority',
  'DAY IN THE LIFE': 'day_in_the_life',
  'RANDOM / ENGAGEMENT': 'random_engagement',
};

// Hooks that tend to be outlier performers (pattern-matched)
const OUTLIER_PATTERNS = [
  /\bif I woke up\b/i,
  /\bI am going to tell you\b/i,
  /\bI messed up\b/i,
  /\bno one talks about\b/i,
  /\bstop doing\b/i,
  /\bI'm only\b/i,
  /\bmy biggest regret\b/i,
  /\bchange my life\b/i,
  /\bscarest thing\b/i,
  /\bI quit\b/i,
  /\bfrom 0 to\b/i,
  /\boutlier\b/i,
  /\bwhat if I told you\b/i,
  /\b5x\b/i,
  /\bproof\b/i,
];

function countPlaceholders(template: string): number {
  const matches = template.match(/\(insert [^)]+\)/gi);
  return matches ? matches.length : 0;
}

function isOutlier(template: string): boolean {
  return OUTLIER_PATTERNS.some((p) => p.test(template));
}

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

interface HookRow {
  category: string;
  template: string;
  placeholder_count: number;
  is_outlier: boolean;
  performance_score: number;
}

function parseHooks(md: string): HookRow[] {
  const rows: HookRow[] = [];
  let currentCategory = '';

  const lines = md.replace(/\r/g, '').split('\n');

  for (const line of lines) {
    // Detect section heading — ## CATEGORY NAME
    const headingMatch = line.match(/^## ([A-Z\/]+(?:\s+[A-Z\/]+)*)\s*$/);
    if (headingMatch) {
      const heading = headingMatch[1].trim();
      if (CATEGORY_MAP[heading]) {
        currentCategory = CATEGORY_MAP[heading];
      }
      continue;
    }

    // Skip table of contents and other non-template lines
    if (!currentCategory) continue;

    // Match numbered list items: "123. Template text here"
    const itemMatch = line.match(/^\d+\.\s+(.+)$/);
    if (!itemMatch) continue;

    const template = itemMatch[1].trim();
    if (!template || template.length < 5) continue;

    const placeholder_count = countPlaceholders(template);
    const outlier = isOutlier(template);

    // Score heuristic: outliers +2, has placeholders +1, length sweet-spot (30-120 chars) +1
    let score = 5.0;
    if (outlier) score += 2.0;
    if (placeholder_count > 0 && placeholder_count <= 4) score += 1.0;
    if (template.length >= 30 && template.length <= 120) score += 1.0;
    if (template.includes('?')) score += 0.5; // questions tend to engage
    score = Math.min(10, score);

    rows.push({
      category: currentCategory,
      template,
      placeholder_count,
      is_outlier: outlier,
      performance_score: parseFloat(score.toFixed(2)),
    });
  }

  return rows;
}

function buildSQL(rows: HookRow[]): string {
  const header = `-- supabase/migrations/003_seed_hooks_library.sql
-- Auto-generated by scripts/parse-hooks.ts
-- ${rows.length} hooks parsed from hooks-library.md
-- Run this ONCE against your Supabase project after 001_initial_schema.sql

-- Clear existing seeded hooks to allow idempotent re-runs
DELETE FROM public.hooks WHERE id IS NOT NULL;

INSERT INTO public.hooks (category, template, placeholder_count, is_outlier, performance_score, use_count)
VALUES`;

  const valueRows = rows.map((r) => {
    const tpl = escapeSQL(r.template);
    return `  ('${r.category}', '${tpl}', ${r.placeholder_count}, ${r.is_outlier}, ${r.performance_score}, 0)`;
  });

  return `${header}\n${valueRows.join(',\n')};\n`;
}

// ─── Main ─────────────────────────────────────────────────
const md = fs.readFileSync(INPUT_PATH, 'utf-8');
const rows = parseHooks(md);

console.log(`Parsed ${rows.length} hooks across categories:`);
const byCat: Record<string, number> = {};
for (const r of rows) {
  byCat[r.category] = (byCat[r.category] || 0) + 1;
}
for (const [cat, count] of Object.entries(byCat)) {
  console.log(`  ${cat}: ${count}`);
}

const sql = buildSQL(rows);
fs.writeFileSync(OUTPUT_PATH, sql, 'utf-8');
console.log(`\nWrote ${OUTPUT_PATH}`);
